# Workflow used as Continous Integration every time we have a PR.
name: CI

on:
  # Only build when pushed to master
  push:
    branches:
    - master
  # Build all pull requests
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.40.1
    
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We only support the latest version of all platforms.
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        go:
        - "1.16"
        - "1.17"
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build ./...
    - name: Run Unit Tests
      run: go test ./...
  
